- name: http
  sourceDefinitionId: f20a3c02-c70e-4e76-8566-7c13ca11d18d
  documentationUrl: https://docs.instill.tech/integrations/sources/http
  icon: http.svg
  sourceType: directness
- name: gRPC
  sourceDefinitionId: 82ca7d29-a35c-4222-b900-8d6878195e7a
  documentationUrl: https://docs.instill.tech/integrations/sources/grpc
  icon: grpc.svg
  sourceType: directness
