- dockerImage: instill-ai/destination-http
  spec:
    documentationUrl: https://docs.instill.tech/connectors/definitions/destination-http
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      additionalProperties: false
      properties: {}
      required: []
      title: HTTP Destination Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
- dockerImage: instill-ai/destination-grpc
  spec:
    documentationUrl: https://docs.instill.tech/connectors/definitions/destination-grpc
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      additionalProperties: false
      properties: {}
      required: []
      title: gRPC Destination Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
