- dockerImage: instill-ai/source-http:directness
  spec:
    documentationUrl: https://docs.instill.tech/connectors/definitions/source-http-directness
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      additionalProperties: false
      properties: {}
      required: []
      title: Directness HTTP Source Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
- dockerImage: instill-ai/source-grpc:directness
  spec:
    documentationUrl: https://docs.instill.tech/connectors/definitions/source-grpc-directness
    connectionSpecification:
      $schema: http://json-schema.org/draft-07/schema#
      additionalProperties: false
      properties: {}
      required: []
      title: Directness gRPC Source Connector Spec
      type: object
    supportsIncremental: false
    supportsNormalization: false
    supportsDBT: false
    supported_destination_sync_modes: []
