server:
  port: 8082
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
  corsorigins:
    - http://localhost
    - https://instill-inc.tech
    - https://instill.tech
  edition: local-ce:dev
  disableusage: true
  debug: false
database:
  username: postgres
  password: password
  host: localhost
  port: 5432
  name: connector
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
temporal:
  clientoptions:
    hostport: localhost:7233
mgmtbackend:
  host: localhost
  port: 8080
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
usagebackend:
  host: usage.instill.tech
  port: 443
