server:
  port: 8082
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
  corsorigins:
    - http://localhost
    - https://instill-inc.tech
    - https://instill.tech
  edition: local-ce:dev
  disableusage: false
  debug: true
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: connector
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
temporal:
  clientoptions:
    hostport: temporal:7233
mgmtbackend:
  host: mgmt-backend
  port: 8080
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
pipelinebackend:
  host: pipeline-backend
  port: 8081
  https:
    cert:   # /ssl/tls.crt
    key:    # /ssl/tls.key
usagebackend:
  tlsenabled: true
  host: usage.instill.tech
  port: 443
